#

FROM node:14-alpine

LABEL maintainer="wxxiong <wxxiong6@gmail.com>" version="14-alpine" description="node:14-alpine"


ENV TZ "Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


