FROM node:16-alpine

LABEL maintainer="wxxiong <wxxiong6@gmail.com>" version="16-alpine" description="16-alpine"


ENV TZ "Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


