FROM line/kubectl-kustomize:1.25.0-4.5.7

LABEL maintainer="wxxiong <wxxiong6@gmail.com>" version="1.25.0-4.5.7" description="1.25.0-4.5.7"


ENV TZ "Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


